CREATE TABLE public.organisation (
	id serial4 NOT NULL,
	user_id uuid DEFAULT uuid_generate_v4() NULL,
	"name" text NOT NULL,
	legal_name text NULL,
	"type" text NULL,
	industry text NULL,
	country text NULL,
	headquarters text NULL,
	founding_date date NULL,
	founder text NULL,
	ceo text NULL,
	employees int4 NULL,
	revenue numeric(15, 2) NULL,
	net_income numeric(15, 2) NULL,
	assets numeric(15, 2) NULL,
	website text NULL,
	stock_symbol text NULL,
	parent_company text NULL,
	subsidiaries jsonb DEFAULT '{}'::jsonb NULL,
	description text NULL,
	address jsonb NULL,
	additional_attributes jsonb DEFAULT '{}'::jsonb NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	embedding public.vector NULL,
	embedding_ada public.vector NULL,
	CONSTRAINT organisation_pkey PRIMARY KEY (id)
);