CREATE TABLE public.person (
	id serial4 NOT NULL,
	user_id uuid DEFAULT uuid_generate_v4() NULL,
	"name" text NOT NULL,
	birth_date date NULL,
	birth_place text NULL,
	death_date date NULL,
	death_place text NULL,
	nationality text NULL,
	occupation text NULL,
	spouse text NULL,
	children _text NULL,
	alma_mater text NULL,
	notable_work _text NULL,
	awards _text NULL,
	abstract text NULL,
	"source" text NULL,
	history text NULL,
	additional_attributes jsonb DEFAULT '{}'::jsonb NULL,
	description text NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	embedding public.vector NULL,
	CONSTRAINT person_pkey PRIMARY KEY (id)
);